# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
